num1 = input('Enter first number: ')
num2 = input('Enter second number: ')
sum = float(num1) + float(num2)
print('The sum of {0} and {1} is {2}'.format(num1, num2, sum))
min = float(num1) - float(num2)
print('The subtraction of {0} and {1} is {2}'.format(num1, num2, min))
Mul = float(num1) * float(num2)
print('The multiplication of {0} and {1} is {2}'.format(num1, num2, Mul))
div = float(num1) / float(num2)
print('The division of {0} and {1} is {2}'.format(num1, num2, div))